#!/usr/bin/php
<?php

ini_set('error_reporting', E_ALL);
ini_set('display_errors', true);
ini_set('memory_limit', '2048m');

require 'vendor/autoload.php';

use Bot\Command\RawCommandParser;
use Bot\Position;
use Bot\Direction;
use Bot\Bot;

if (! isset($argv[1])) {
    die('No command line argument supplied' . PHP_EOL);
}

$initialPosition = new Position();
$initialDirection = new Direction(Direction::NORTH);
$command = $argv[1];
$commandParser = new RawCommandParser();

$bot = new Bot($initialPosition, $initialDirection, $command, $commandParser);
$endDetails = $bot->executeCommand();

print_r($endDetails);
echo PHP_EOL;
